apiVersion: 1

datasources:
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    jsonData:
      nodeGraph:
        enabled: true
    editable: true
    isDefault: false
